-- MySQL Script generated by MySQL Workbench
-- Thu Mar 10 08:22:48 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`subjekt`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`subjekt` ;

CREATE TABLE IF NOT EXISTS `mydb`.`subjekt` (
  `idsubjekt` INT NOT NULL,
  `jmeno` VARCHAR(45) NULL,
  `prijmeni` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idsubjekt`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`certifikát`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`certifikát` ;

CREATE TABLE IF NOT EXISTS `mydb`.`certifikát` (
  `idcertifikát` INT NOT NULL,
  `RSA_klic` VARCHAR(45) NULL,
  `expirace` DATE NULL,
  `subjekt_idsubjekt` INT NOT NULL,
  PRIMARY KEY (`idcertifikát`),
  CONSTRAINT `fk_certifikát_subjekt`
    FOREIGN KEY (`subjekt_idsubjekt`)
    REFERENCES `mydb`.`subjekt` (`idsubjekt`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_certifikát_subjekt_idx` ON `mydb`.`certifikát` (`subjekt_idsubjekt` ASC);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
